import { Box, Group, Title, Image } from "@mantine/core";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/about")({
    component: () => AboutPage(),
});

function AboutPage() {
    return (
        <Box>
            <Group style={{ textAlign: "right", paddingTop: "5rem", paddingRight: "1rem" }}>
                <Title
                    order={1}
                    style={{ fontFamily: "Noe Bold", fontSize: "10em", lineHeight: "1em", color: "var(--mantine-color-green-8)", width: "100%" }}
                >
                    Who We Are
                </Title>
            </Group>
            <Box style={{ display:"flex", 
                background:"linear-gradient(var(--mantine-color-green-5), var(--mantine-color-green-3) 5%, var(--mantine-color-green-3) 95%, var(--mantine-color-green-5))" }}>
                <Image src="/landing-page.jpg" h="auto" w="28vw" style={{marginLeft: "0px", marginRight:"auto" }} />
                <Box style={{ display: "flex", flexDirection: "column", width: "70%", marginLeft: "auto", marginRight:"0px" }}>
                    {missionText()}
                    {pointsOfUnityText()}
                </Box>
            </Box> 
            <Box style={{width:"100%"}}>
            <Title
                    order={1}
                    style={{ fontFamily: "Noe Bold", fontSize: "10em", lineHeight: "1em", color: "var(--mantine-color-green-8)", width: "100%", textAlign:"center" }}
                >
                    Our Constitution
                </Title>
                {/** embed constitution in an iframe here */}
            </Box>
        </Box>
        
    );
}

function missionText(){
    return(
        <Box>
            <Group style={{ display: "block", textAlign: "right", paddingTop: "2rem", paddingRight: "1rem", width: "100%", marginLeft: "auto", marginRight: "0px" }}>
                <hr style={{ color: "white", width: "60%", marginLeft: "auto", marginRight: "0px" }} />
                <Title
                    order={1}
                    style={{ fontFamily: "Noe Bold", fontSize: "5em", lineHeight: "1em", color: "var(--mantine-color-green-8)", marginLeft: "auto", overflow: "visible" }}
                >
                    Our Mission
                </Title>
                <p style={{ fontWeight: "bold", fontSize: "1.25em", lineHeight: "1.25em", color: "var(--mantine-color-green-8)", marginLeft: "auto", textAlign: "left", paddingTop: "2rem" }}>
                    Coming off the momentum generated by the Spring 2024 Student Intifada, Students for Justice in Palestine at Rochester Institute of Technology was founded to make space for students and community members to agitate, educate, and organize around the broader Palestinian solidarity movement. Our goals are as follows:
                    <ol>
                        <li>Educate community members on the history of the Palestinian struggle since 1948 through means such as public seminar and social media engagement.</li>
                        <li>Identify local collaborators of the ongoing genocide in Gaza, like so-called “defense contractors”, and provide students with resources to avoid supporting these institutions while enrolled at RIT.</li>
                        <li>Agitate, demonstrate, and otherwise make our voices heard on the RIT campus and within the greater Rochester community when necessary to enact lasting change.</li>
                        <li>Express solidarity with members of the community that share our mission.</li>
                    </ol>
                </p>
            </Group>
        </Box>
    );
}

function pointsOfUnityText(){
    return(
        <Box>
            <Group style={{ display: "block", textAlign: "right", paddingTop: "2rem", paddingRight: "1rem", width: "100%", marginLeft: "auto", marginRight: "0px" }}>
                <hr style={{ color: "white", width: "80%", marginLeft: "auto", marginRight: "0px" }} />
                <Title
                    order={1}
                    style={{ fontFamily: "Noe Bold", fontSize: "5em", lineHeight: "1em", color: "var(--mantine-color-green-8)", marginLeft: "auto", overflow: "visible" }}
                >
                    Our Points of Unity
                </Title>
                <p style={{ fontWeight: "bold", fontSize: "1.25em", lineHeight: "1.25em", color: "var(--mantine-color-green-8)", marginLeft: "auto", textAlign: "left", paddingTop: "2rem" }}>
                    <ol>
                        <li>
                            Palestinians have the right to self determination on their homeland of Palestine.
                        </li>
                        <li>
                            Zionism is a manifestation of settler colonialism which engages in an apartheid system against Palestinians.
                        </li>
                        <li>
                            Palestinians are an occupied people, and as such have a right to resist their occupation by any means deemed necessary as described in the 1970 United Nations General Assembly Resolution 2625.
                        </li>
                        <li>
                            Palestinians and their descendents have a right to return which shall not be infringed as described in UN Resolution 194.
                        </li>
                        <li>
                        The movement for a free Palestine is an anti-imperialist, anti-racist, anti-capitalist, internationalist, and intersectional movement. This makes it inseparable from the liberation movements of all oppressed peoples, including Black, Hispanic, and Native Americans, queer and disabled people, workers, and oppressed peoples of every nation.
                        </li>
                    </ol>
                </p>
            </Group>
        </Box>
    );
}
